export const fonts = {
	supported: [
		"Adventurer",
		"Alfonso-X",
		"Alpha2",
		"Assistant",
		"Berlin",
		"Cases",
		"Chess-7",
		"Condal",
		"Harlequin",
		"Kingdom",
		"Leipzig",
		"Line",
		"Lucena",
		"Magnetic",
		"Mark",
		"Marroquin",
		"Maya",
		"Mediaeval",
		"Merida",
		"Millenia Light",
		"Millenia Dark",
		"Regular",
		"Smart",
		"Tasc",
		"Traveller",
	],
	unsupported: ["Alpha", "Cheq", "Echecs", "Miscel", "Pirat"],
};
